# Generated by Django 2.1 on 2018-08-23 14:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20180822_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_like',
            field=models.IntegerField(default=666, verbose_name='点赞次数'),
        ),
        migrations.AddField(
            model_name='article',
            name='click_unlike',
            field=models.IntegerField(default=0, verbose_name='不赞次数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar/default.png', max_length=200, null=True, upload_to='media/avator/%Y/%m', verbose_name='用户头像'),
        ),
    ]
